server:
  port: 8060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.118.202:3306/imooc-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 369852147lbt

  redis:
    host: 47.98.118.202
    database: 0
    port: 6379
    password: 1234

security:
  basic:
    enabled: false
